import { v4 as uuidv4 } from 'uuid'
import db from '../db.js'
import { sendNotificationBundle } from './notifications.js'

function getSettingValue(settings, key, fallback = '') {
  const row = settings.find(s => s.settingKey === key || s.settingkey === key)
  return row?.settingValue ?? row?.settingvalue ?? fallback
}

function getDateRange(rangeType) {
  const now = new Date()
  let start, end

  switch (rangeType) {
    case 'today': {
      start = new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString()
      end = now.toISOString()
      break
    }
    case 'yesterday': {
      const yesterday = new Date(now)
      yesterday.setDate(yesterday.getDate() - 1)
      start = new Date(yesterday.getFullYear(), yesterday.getMonth(), yesterday.getDate()).toISOString()
      end = new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString()
      break
    }
    case 'last_24h': {
      start = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString()
      end = now.toISOString()
      break
    }
    case 'this_week': {
      const dayOfWeek = now.getDay()
      const diff = now.getDate() - dayOfWeek + (dayOfWeek === 0 ? -6 : 1)
      start = new Date(now.getFullYear(), now.getMonth(), diff).toISOString()
      end = now.toISOString()
      break
    }
    default: {
      start = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString()
      end = now.toISOString()
    }
  }

  return { start, end }
}

function buildReportHtml(data) {
  const { clientEmail, periodStart, periodEnd, scans, verified, flagged, totalHours } = data
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Patrol Report</title>
<style>
  body { font-family: 'Inter', -apple-system, sans-serif; color: #1a1a1a; padding: 40px; background: #fff; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .sub { color: #666; font-size: 13px; margin-bottom: 24px; }
  .stats { display: flex; gap: 16px; margin-bottom: 28px; }
  .stat { background: #f5f5f5; padding: 14px 20px; border-radius: 10px; flex: 1; }
  .stat .val { font-size: 26px; font-weight: 700; }
  .stat .lbl { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; padding: 10px 12px; border-bottom: 2px solid #e5e5e5; color: #666; font-weight: 600; font-size: 11px; text-transform: uppercase; }
  td { padding: 10px 12px; border-bottom: 1px solid #eee; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
  .badge-v { background: #e6f7e6; color: #166534; }
  .badge-f { background: #fee9e7; color: #b91c1c; }
  .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
</style></head>
<body>
  <h1>Patrol Monitoring Report</h1>
  <div class="sub">${clientEmail} &middot; ${new Date(periodStart).toLocaleDateString()} - ${new Date(periodEnd).toLocaleDateString()}</div>
  <div class="stats">
    <div class="stat"><div class="val">${scans.length}</div><div class="lbl">Total Scans</div></div>
    <div class="stat"><div class="val">${verified}</div><div class="lbl">Verified</div></div>
    <div class="stat"><div class="val">${flagged}</div><div class="lbl">Flagged</div></div>
    <div class="stat"><div class="val">${Math.round(totalHours / 3600000 * 10) / 10}h</div><div class="lbl">Patrol Hours</div></div>
  </div>
  <h2 style="font-size:16px;margin-bottom:12px;">Scan Details</h2>
  <table>
    <tr><th>Time</th><th>Officer</th><th>Checkpoint</th><th>Distance</th><th>Status</th></tr>
    ${scans.map(s => `<tr>
      <td>${new Date(s.scannedAt).toLocaleString()}</td>
      <td>${s.officerName}</td>
      <td>${s.checkpointName} (${s.checkpointCode})</td>
      <td>${s.distanceMeters ? s.distanceMeters + 'm' : '-'}</td>
      <td><span class="badge ${s.gpsValid ? 'badge-v' : 'badge-f'}">${s.gpsValid ? 'Verified' : 'Flagged'}</span></td>
    </tr>`).join('')}
  </table>
  <div class="footer">Generated by Patrol Monitoring System &middot; ${new Date().toISOString()}</div>
</body></html>`
}

async function runAutoEmailCycle() {
  try {
    const settings = await db.all('SELECT * FROM communicationSettings')

    const enabled = getSettingValue(settings, 'auto_report_enabled', 'false')
    if (enabled !== 'true') return

    const scheduleType = getSettingValue(settings, 'auto_report_schedule', 'daily')
    const rangeType = getSettingValue(settings, 'auto_report_range', 'last_24h')
    const recipients = getSettingValue(settings, 'report_email_recipients', '')
      .split(',').map(v => v.trim()).filter(Boolean)

    if (recipients.length === 0) return

    const { start, end } = getDateRange(rangeType)

    const clientIds = await db.all('SELECT DISTINCT clientId FROM checkpoints WHERE clientId IS NOT NULL AND active = 1')

    for (const { clientId } of clientIds) {
      const client = await db.get('SELECT * FROM clients WHERE id = ?', [clientId])
      if (!client) continue

      const scans = await db.all(`
        SELECT s.*, u.name as officerName, c.name as checkpointName, c.code as checkpointCode
        FROM scans s
        JOIN users u ON s.officerId = u.id
        JOIN checkpoints c ON s.checkpointId = c.id
        WHERE s.scannedAt >= ? AND s.scannedAt <= ? AND c.clientId = ?
        ORDER BY s.scannedAt DESC
      `, [start, end, clientId])

      if (scans.length === 0) continue

      const shifts = await db.all(`
        SELECT s.*, u.name as userName FROM shifts s
        JOIN users u ON s.userId = u.id
        WHERE s.clockIn >= ? AND (s.clockOut IS NULL OR s.clockOut <= ?) AND u.clientId = ?
      `, [start, end, clientId])

      const totalHours = shifts.reduce((acc, s) => {
        if (!s.clockOut) return acc
        return acc + (new Date(s.clockOut).getTime() - new Date(s.clockIn).getTime())
      }, 0)

      const verified = scans.filter(s => s.gpsValid).length
      const flagged = scans.length - verified

      const reportData = {
        clientEmail: recipients.join(', '),
        periodStart: start,
        periodEnd: end,
        scans,
        verified,
        flagged,
        totalHours,
      }

      const html = buildReportHtml(reportData)

      const reportId = uuidv4()
      await db.run(`
        INSERT INTO reports (id, clientEmail, periodStart, periodEnd, format, status, sentAt)
        VALUES (?, ?, ?, ?, ?, ?, ?)
      `, [reportId, recipients.join(', '), start, end, 'html', 'sending', null])

      const result = await sendNotificationBundle({
        emails: recipients,
        subject: `Auto Patrol Report — ${new Date(start).toLocaleDateString()} to ${new Date(end).toLocaleDateString()}`,
        html,
        text: `Auto Patrol Report\nPeriod: ${start} — ${end}\nTotal scans: ${scans.length}\nVerified: ${verified}\nFlagged: ${flagged}\nPatrol hours: ${Math.round(totalHours / 3600000 * 10) / 10}h`,
      })

      await db.run(
        `UPDATE reports SET status = ?, sentAt = ? WHERE id = ?`,
        [result.skipped ? 'failed' : 'sent', result.skipped ? null : new Date().toISOString(), reportId]
      )
    }
  } catch (err) {
    console.error('[reportScheduler]', err.message)
  }
}

let intervalHandle = null

export function startReportScheduler(intervalMinutes = 60) {
  if (intervalHandle) return
  console.log(`[reportScheduler] Starting auto-email cycle every ${intervalMinutes} minutes`)
  runAutoEmailCycle()
  intervalHandle = setInterval(runAutoEmailCycle, intervalMinutes * 60 * 1000)
}

export function stopReportScheduler() {
  if (intervalHandle) {
    clearInterval(intervalHandle)
    intervalHandle = null
    console.log('[reportScheduler] Stopped')
  }
}
