import { Router } from 'express'
import { v4 as uuidv4 } from 'uuid'
import db from '../db.js'
import { authMiddleware } from '../middleware/auth.js'

const router = Router()

router.use(authMiddleware)

router.get('/', async (req, res) => {
  const reports = await db.all('SELECT * FROM reports ORDER BY createdAt DESC')
  res.json(reports)
})

router.post('/generate', async (req, res) => {
  const { clientEmail, periodStart, periodEnd, format } = req.body
  if (!clientEmail || !periodStart || !periodEnd) {
    return res.status(400).json({ message: 'clientEmail, periodStart, periodEnd are required' })
  }

  const report = {
    id: uuidv4(),
    clientEmail,
    periodStart,
    periodEnd,
    format: format || 'pdf',
    status: 'pending',
  }

  await db.run(`
    INSERT INTO reports (id, clientEmail, periodStart, periodEnd, format, status)
    VALUES (?, ?, ?, ?, ?, ?)
  `, Object.values(report))

  setTimeout(async () => {
    try {
      await db.run(
        "UPDATE reports SET status = 'sent', sentAt = CURRENT_TIMESTAMP WHERE id = ?",
        [report.id]
      )
    } catch (err) {
      console.error('[reports] Failed to mark report as sent:', err.message)
    }
  }, 2000)

  res.status(201).json(report)
})

router.get('/:id/pdf', async (req, res) => {
  const report = await db.get('SELECT * FROM reports WHERE id = ?', [req.params.id])
  if (!report) return res.status(404).json({ message: 'Report not found' })

  const scans = await db.all(`
    SELECT s.*, u.name as officerName, c.name as checkpointName, c.code as checkpointCode
    FROM scans s
    JOIN users u ON s.officerId = u.id
    JOIN checkpoints c ON s.checkpointId = c.id
    WHERE s.scannedAt >= ? AND s.scannedAt <= ?
    ORDER BY s.scannedAt DESC
  `, [report.periodStart, report.periodEnd])

  const shifts = await db.all(`
    SELECT s.*, u.name as userName FROM shifts s
    JOIN users u ON s.userId = u.id
    WHERE s.clockIn >= ? AND (s.clockOut IS NULL OR s.clockOut <= ?)
  `, [report.periodStart, report.periodEnd])

  const totalHours = shifts.reduce((acc, s) => {
    if (!s.clockOut) return acc
    return acc + (new Date(s.clockOut).getTime() - new Date(s.clockIn).getTime())
  }, 0)

  const verified = scans.filter(s => s.gpsValid).length
  const flagged = scans.length - verified

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Patrol Report</title>
<style>
  body { font-family: 'Inter', -apple-system, sans-serif; color: #1a1a1a; padding: 40px; background: #fff; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .sub { color: #666; font-size: 13px; margin-bottom: 24px; }
  .stats { display: flex; gap: 16px; margin-bottom: 28px; }
  .stat { background: #f5f5f5; padding: 14px 20px; border-radius: 10px; flex: 1; }
  .stat .val { font-size: 26px; font-weight: 700; }
  .stat .lbl { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; padding: 10px 12px; border-bottom: 2px solid #e5e5e5; color: #666; font-weight: 600; font-size: 11px; text-transform: uppercase; }
  td { padding: 10px 12px; border-bottom: 1px solid #eee; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
  .badge-v { background: #e6f7e6; color: #166534; }
  .badge-f { background: #fee9e7; color: #b91c1c; }
  .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
</style></head>
<body>
  <h1>Patrol Monitoring Report</h1>
  <div class="sub">${report.clientEmail} &middot; ${new Date(report.periodStart).toLocaleDateString()} - ${new Date(report.periodEnd).toLocaleDateString()}</div>
  <div class="stats">
    <div class="stat"><div class="val">${scans.length}</div><div class="lbl">Total Scans</div></div>
    <div class="stat"><div class="val">${verified}</div><div class="lbl">Verified</div></div>
    <div class="stat"><div class="val">${flagged}</div><div class="lbl">Flagged</div></div>
    <div class="stat"><div class="val">${Math.round(totalHours / 3600000 * 10) / 10}h</div><div class="lbl">Patrol Hours</div></div>
  </div>
  <h2 style="font-size:16px;margin-bottom:12px;">Scan Details</h2>
  <table>
    <tr><th>Time</th><th>Officer</th><th>Checkpoint</th><th>Distance</th><th>Status</th></tr>
    ${scans.map(s => `<tr>
      <td>${new Date(s.scannedAt).toLocaleString()}</td>
      <td>${s.officerName}</td>
      <td>${s.checkpointName} (${s.checkpointCode})</td>
      <td>${s.distanceMeters ? s.distanceMeters + 'm' : '-'}</td>
      <td><span class="badge ${s.gpsValid ? 'badge-v' : 'badge-f'}">${s.gpsValid ? 'Verified' : 'Flagged'}</span></td>
    </tr>`).join('')}
  </table>
  <div class="footer">Generated by Patrol Monitoring System &middot; ${new Date().toISOString()}</div>
</body></html>`

  res.setHeader('Content-Type', 'text/html')
  res.send(html)
})

export default router
